import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'auth_gate.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SwapCycleApp());
}

class SwapCycleApp extends StatelessWidget {
  const SwapCycleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SwapCycle',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
        useMaterial3: true,
      ),
      home: const AuthGate(), // was ListingFeedScreen()
    );
  }
}

class Listing {
  final String id;
  final String owner;
  final String item;
  final String category;
  final String brand;
  final String condition;

  const Listing({
    required this.id,
    required this.owner,
    required this.item,
    required this.category,
    required this.brand,
    required this.condition,
  });

  // Keeps the same field names your Python prototype's user/listing dicts
  // use, so this maps straight onto normalize_preference()'s expected shape
  // once the bridge is built.
  factory Listing.fromFirestore(DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data()!;
    return Listing(
      id: doc.id,
      owner: data['ownerId'] as String? ?? '',
      item: data['item'] as String? ?? '',
      category: data['category'] as String? ?? '',
      brand: data['brand'] as String? ?? '',
      condition: data['condition'] as String? ?? '',
    );
  }
}

class ListingFeedScreen extends StatelessWidget {
  const ListingFeedScreen({super.key});

  IconData _iconForCategory(String category) {
    switch (category.toLowerCase()) {
      case 'bicycle':
        return Icons.pedal_bike;
      case 'guitar':
        return Icons.music_note;
      case 'camera':
        return Icons.camera_alt;
      default:
        return Icons.inventory_2;
    }
  }

  @override
  Widget build(BuildContext context) {
    final listingsRef = FirebaseFirestore.instance
        .collection('listings')
        .orderBy('item');

    return Scaffold(
      appBar: AppBar(
        title: const Text('SwapCycle'),
        centerTitle: true,
        actions: [
          IconButton(
            icon: const Icon(Icons.sync_alt),
            tooltip: 'My Matches',
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => const MatchResultScreen(),
                ),
              );
            },
          ),
          IconButton(
            icon: const Icon(Icons.logout),
            tooltip: 'Sign out',
            onPressed: () => FirebaseAuth.instance.signOut(),
          ),
        ],
      ),
      body: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
        stream: listingsRef.snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(child: Text('Error loading listings: ${snapshot.error}'));
          }
          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }

          final docs = snapshot.data!.docs;
          if (docs.isEmpty) {
            return const Center(
              child: Padding(
                padding: EdgeInsets.all(24),
                child: Text(
                  'No listings yet. Tap the + button below to add one.',
                  textAlign: TextAlign.center,
                ),
              ),
            );
          }

          final listings = docs.map(Listing.fromFirestore).toList();

          return ListView.builder(
            padding: const EdgeInsets.all(12),
            itemCount: listings.length,
            itemBuilder: (context, index) {
              final listing = listings[index];
              return Card(
                margin: const EdgeInsets.symmetric(vertical: 6),
                child: ListTile(
                  leading: CircleAvatar(
                    child: Icon(_iconForCategory(listing.category)),
                  ),
                  title: Text('${listing.item} — ${listing.brand}'),
                  subtitle: Text('Owned by ${listing.owner} · ${listing.condition} condition'),
                  trailing: const Icon(Icons.chevron_right),
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => const PreferenceInputScreen(),
                      ),
                    );
                  },
                ),
              );
            },
          );
        },
      ),
      floatingActionButton: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        crossAxisAlignment: CrossAxisAlignment.end,
        children: [
          FloatingActionButton.extended(
            heroTag: 'addListingFab',
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => const AddListingScreen(),
                ),
              );
            },
            icon: const Icon(Icons.add_box_outlined),
            label: const Text('Add Listing'),
          ),
          const SizedBox(height: 12),
          FloatingActionButton.extended(
            heroTag: 'requestSwapFab',
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => const PreferenceInputScreen(),
                ),
              );
            },
            icon: const Icon(Icons.search),
            label: const Text('Request Swap'),
          ),
        ],
      ),
    );
  }
}

class PreferenceInputScreen extends StatefulWidget {
  const PreferenceInputScreen({super.key});

  @override
  State<PreferenceInputScreen> createState() => _PreferenceInputScreenState();
}

class _PreferenceInputScreenState extends State<PreferenceInputScreen> {
  final TextEditingController _controller = TextEditingController();
  bool _submitting = false;
  String? _submittedText;
  String? _error;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _submitPreference() async {
    final text = _controller.text.trim();
    if (text.isEmpty) return;

    setState(() {
      _submitting = true;
      _error = null;
    });

    try {
      // Schema deliberately mirrors the input `normalize_preference()`
      // expects on the Python side, plus a status flag so a future
      // Cloud Function trigger knows which docs still need processing.
      final uid = FirebaseAuth.instance.currentUser!.uid;
      await FirebaseFirestore.instance.collection('preferences').add({
        'userId': uid, // required by firestore.rules: create check compares this to auth.uid
        'rawText': text,
        'submittedAt': FieldValue.serverTimestamp(),
        'status': 'pending', // pending -> processed once AI bridge exists
      });

      setState(() {
        _submittedText = text;
        _controller.clear();
      });
    } catch (e) {
      setState(() {
        _error = 'Failed to submit: $e';
      });
    } finally {
      setState(() {
        _submitting = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('What are you looking for?')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Text(
              'Describe what you want in your own words. '
              'This gets normalized by SwapCycle\'s AI before matching.',
              style: TextStyle(color: Colors.grey),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _controller,
              maxLines: 3,
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                hintText: 'e.g. I want a beginner-friendly Yamaha guitar, good condition is fine.',
              ),
            ),
            const SizedBox(height: 12),
            ElevatedButton(
              onPressed: _submitting ? null : _submitPreference,
              child: _submitting
                  ? const SizedBox(
                      height: 18,
                      width: 18,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Text('Submit Preference'),
            ),
            if (_error != null) ...[
              const SizedBox(height: 12),
              Text(_error!, style: const TextStyle(color: Colors.red)),
            ],
            if (_submittedText != null) ...[
              const SizedBox(height: 24),
              const Text('Saved to Firestore (preferences collection):',
                  style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Card(
                color: Theme.of(context).colorScheme.surfaceContainerHighest,
                child: Padding(
                  padding: const EdgeInsets.all(12),
                  child: Text(_submittedText!),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}

/// Lets a signed-in user list an item they own so it can be matched
/// against other users' preferences. Writes directly to the `listings`
/// collection with `ownerId` set to the current auth UID and
/// `status: 'active'` so it's immediately picked up by
/// `firestore_bridge.py`'s active-listings query.
class AddListingScreen extends StatefulWidget {
  const AddListingScreen({super.key});

  @override
  State<AddListingScreen> createState() => _AddListingScreenState();
}

class _AddListingScreenState extends State<AddListingScreen> {
  final _formKey = GlobalKey<FormState>();
  final _itemController = TextEditingController();
  final _brandController = TextEditingController();
  String _category = 'guitar';
  String _condition = 'good';
  bool _submitting = false;
  String? _error;
  bool _submitted = false;

  static const _categories = [
    'guitar',
    'camera',
    'bicycle',
    'book',
    'electronics',
    'clothing',
    'other',
  ];

  static const _conditions = [
    'new',
    'like new',
    'good',
    'fair',
    'poor',
  ];

  @override
  void dispose() {
    _itemController.dispose();
    _brandController.dispose();
    super.dispose();
  }

  Future<void> _submitListing() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() {
      _submitting = true;
      _error = null;
    });

    try {
      final uid = FirebaseAuth.instance.currentUser!.uid;
      await FirebaseFirestore.instance.collection('listings').add({
        // Field name matches firestore_schema.md and Listing.fromFirestore
        // above — this is the field the bridge script queries on.
        'ownerId': uid,
        'item': _itemController.text.trim(),
        'category': _category,
        'brand': _brandController.text.trim(),
        'condition': _condition,
        'status': 'active',
        'createdAt': FieldValue.serverTimestamp(),
      });

      setState(() {
        _submitted = true;
        _itemController.clear();
        _brandController.clear();
      });
    } catch (e) {
      setState(() {
        _error = 'Failed to add listing: $e';
      });
    } finally {
      setState(() {
        _submitting = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Add a Listing')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              const Text(
                'List something you own that you\'d be willing to swap.',
                style: TextStyle(color: Colors.grey),
              ),
              const SizedBox(height: 16),
              TextFormField(
                controller: _itemController,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Item name',
                  hintText: 'e.g. Acoustic Guitar',
                ),
                validator: (value) =>
                    (value == null || value.trim().isEmpty) ? 'Required' : null,
              ),
              const SizedBox(height: 12),
              DropdownButtonFormField<String>(
                initialValue: _category,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Category',
                ),
                items: _categories
                    .map((c) => DropdownMenuItem(value: c, child: Text(c)))
                    .toList(),
                onChanged: (value) => setState(() => _category = value!),
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _brandController,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Brand',
                  hintText: 'e.g. Yamaha',
                ),
                validator: (value) =>
                    (value == null || value.trim().isEmpty) ? 'Required' : null,
              ),
              const SizedBox(height: 12),
              DropdownButtonFormField<String>(
                initialValue: _condition,
                decoration: const InputDecoration(
                  border: OutlineInputBorder(),
                  labelText: 'Condition',
                ),
                items: _conditions
                    .map((c) => DropdownMenuItem(value: c, child: Text(c)))
                    .toList(),
                onChanged: (value) => setState(() => _condition = value!),
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _submitting ? null : _submitListing,
                child: _submitting
                    ? const SizedBox(
                        height: 18,
                        width: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Text('Add Listing'),
              ),
              if (_error != null) ...[
                const SizedBox(height: 12),
                Text(_error!, style: const TextStyle(color: Colors.red)),
              ],
              if (_submitted) ...[
                const SizedBox(height: 12),
                const Text(
                  'Listing added! It\'s now active and visible in the feed.',
                  style: TextStyle(color: Colors.green),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}

/// Shows any exchange cycles the current user is part of. Reads directly
/// from the `matches` collection written by `firestore_bridge.py` —
/// filters on `cycle` containing the signed-in user's UID.
class MatchResultScreen extends StatelessWidget {
  const MatchResultScreen({super.key});

  Future<Listing?> _fetchListing(String listingId) async {
    final doc = await FirebaseFirestore.instance
        .collection('listings')
        .doc(listingId)
        .get();
    if (!doc.exists) return null;
    return Listing.fromFirestore(doc);
  }

  @override
  Widget build(BuildContext context) {
    final uid = FirebaseAuth.instance.currentUser!.uid;
    final matchesRef = FirebaseFirestore.instance
        .collection('matches')
        .where('cycle', arrayContains: uid);

    return Scaffold(
      appBar: AppBar(title: const Text('My Matches')),
      body: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
        stream: matchesRef.snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(child: Text('Error loading matches: ${snapshot.error}'));
          }
          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }

          final docs = snapshot.data!.docs;
          if (docs.isEmpty) {
            return const Center(
              child: Padding(
                padding: EdgeInsets.all(24),
                child: Text(
                  'No matches yet. Submit a preference and check back '
                  'after the next matching run.',
                  textAlign: TextAlign.center,
                ),
              ),
            );
          }

          return ListView.builder(
            padding: const EdgeInsets.all(12),
            itemCount: docs.length,
            itemBuilder: (context, index) {
              final data = docs[index].data();
              final cycle = List<String>.from(data['cycle'] as List? ?? []);
              final listingIds =
                  List<String>.from(data['listingIds'] as List? ?? []);
              final utility = (data['totalUtility'] as num?)?.toDouble();
              final fairness = (data['egalitarianScore'] as num?)?.toDouble();
              final status = data['status'] as String? ?? 'pending';

              return Card(
                margin: const EdgeInsets.symmetric(vertical: 8),
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        children: [
                          const Icon(Icons.sync_alt, color: Colors.teal),
                          const SizedBox(width: 8),
                          Text(
                            'Exchange cycle (${cycle.length}-way)',
                            style: const TextStyle(fontWeight: FontWeight.bold),
                          ),
                          const Spacer(),
                          Chip(label: Text(status)),
                        ],
                      ),
                      const SizedBox(height: 8),
                      Text('Participants: ${cycle.join(' → ')} → ${cycle.first}'),
                      const SizedBox(height: 8),
                      ...listingIds.map(
                        (id) => FutureBuilder<Listing?>(
                          future: _fetchListing(id),
                          builder: (context, snap) {
                            if (!snap.hasData) {
                              return const Padding(
                                padding: EdgeInsets.symmetric(vertical: 4),
                                child: LinearProgressIndicator(),
                              );
                            }
                            final listing = snap.data;
                            if (listing == null) {
                              return const SizedBox.shrink();
                            }
                            return Padding(
                              padding: const EdgeInsets.symmetric(vertical: 2),
                              child: Text(
                                '• ${listing.item} (${listing.brand}) — from ${listing.owner}',
                              ),
                            );
                          },
                        ),
                      ),
                      const SizedBox(height: 8),
                      if (utility != null)
                        Text('Total utility: ${utility.toStringAsFixed(2)}'),
                      if (fairness != null)
                        Text('Fairness score: ${fairness.toStringAsFixed(2)}'),
                    ],
                  ),
                ),
              );
            },
          );
        });
  }
}