import json
import os

import requests
from dotenv import load_dotenv


load_dotenv()

URL = "https://openrouter.ai/api/v1/chat/completions"

MODEL = os.getenv(
    "OPENROUTER_MODEL",
    "google/gemini-2.5-flash-lite",
)


SYSTEM = """
You are SwapCycle's bounded candidate-evaluation component.

Your ONLY job is to evaluate exchange-cycle candidates that have already
been generated by the deterministic BGCC matching system.

IMPORTANT RULES:

- You may ONLY recommend one candidate ID that appears in the supplied data.
- Do NOT create a new cycle.
- Do NOT modify a cycle.
- Do NOT add participants.
- Do NOT remove participants.
- Do NOT perform graph matching.
- Do NOT invent candidate IDs.
- Do NOT override BGCC.
- Do NOT assume candidates that were not supplied.
- Evaluate the supplied candidates using:
    1. total utility,
    2. egalitarian fairness,
    3. cycle length,
    4. satisfaction of the normalized preferences.
- Your recommendation is ADVISORY.
- BGCC remains the authoritative deterministic matching engine.
- Return JSON only.

Return exactly:

{
  "recommended_candidate": 1,
  "reason": "short explanation",
  "strengths": ["..."],
  "tradeoffs": ["..."],
  "confidence": 0.0
}

The recommended_candidate MUST be one of the supplied candidate numbers.

confidence must be between 0.0 and 1.0.
"""


def validate_result(result, candidate_count):

    if not isinstance(result, dict):
        raise ValueError(
            "Gemini #2 did not return a JSON object."
        )

    required_fields = {
        "recommended_candidate",
        "reason",
        "strengths",
        "tradeoffs",
        "confidence",
    }

    missing = (
        required_fields
        - result.keys()
    )

    if missing:

        raise ValueError(
            "Gemini #2 response is missing fields: "
            f"{sorted(missing)}"
        )

    candidate_id = result[
        "recommended_candidate"
    ]

    if (
        isinstance(candidate_id, bool)
        or not isinstance(candidate_id, int)
        or not (
            1 <= candidate_id
            <= candidate_count
        )
    ):

        raise ValueError(
            "Gemini #2 attempted to recommend "
            "a candidate that was not supplied."
        )

    if not isinstance(
        result["strengths"],
        list,
    ):

        raise ValueError(
            "strengths must be a JSON list."
        )

    if not isinstance(
        result["tradeoffs"],
        list,
    ):

        raise ValueError(
            "tradeoffs must be a JSON list."
        )

    try:

        confidence = float(
            result["confidence"]
        )

    except (
        TypeError,
        ValueError,
    ) as exc:

        raise ValueError(
            "confidence must be numeric."
        ) from exc

    if not (
        0.0 <= confidence <= 1.0
    ):

        raise ValueError(
            "confidence must be between "
            "0.0 and 1.0."
        )

    result["confidence"] = round(
        confidence,
        2,
    )

    return result


def evaluate_candidates(
    preferences,
    candidates,
):
    """
    Evaluate ONLY candidates generated by BGCC.

    Gemini cannot create, modify or override a cycle.
    """

    api_key = os.getenv(
        "OPENROUTER_API_KEY"
    )

    if not api_key:

        raise RuntimeError(
            "OPENROUTER_API_KEY is not configured."
        )

    payload = {
        "preferences": preferences,
        "candidates": candidates,
    }

    response = requests.post(
        URL,
        headers={
            "Authorization":
                f"Bearer {api_key}",
            "Content-Type":
                "application/json",
        },
        json={
            "model": MODEL,

            "messages": [

                {
                    "role": "system",
                    "content": SYSTEM,
                },

                {
                    "role": "user",
                    "content": json.dumps(
                        payload,
                        ensure_ascii=False,
                    ),
                },
            ],

            "response_format": {
                "type": "json_object"
            },

            "temperature": 0,
        },

        timeout=60,
    )

    response.raise_for_status()

    data = response.json()

    try:

        content = data[
            "choices"
        ][0][
            "message"
        ][
            "content"
        ]

    except (
        KeyError,
        IndexError,
        TypeError,
    ) as exc:

        raise RuntimeError(
            "Unexpected OpenRouter response format."
        ) from exc

    try:

        result = json.loads(
            content
        )

    except json.JSONDecodeError as exc:

        raise RuntimeError(
            "Gemini #2 did not return valid JSON."
        ) from exc

    return validate_result(
        result,
        len(candidates),
    )