// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYfbep-1t1jRfBin9EnsP7QwEeSYZtE-g',
    appId: '1:598228048901:web:8e370c9a050ac5a2d0106c',
    messagingSenderId: '598228048901',
    projectId: 'swapcycle',
    authDomain: 'swapcycle.firebaseapp.com',
    storageBucket: 'swapcycle.firebasestorage.app',
    measurementId: 'G-5C6RDCT5E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR6s-Q2t-097DxXFhVnTSyHgGCWRun4io',
    appId: '1:598228048901:android:1b1dcf0cab541e75d0106c',
    messagingSenderId: '598228048901',
    projectId: 'swapcycle',
    storageBucket: 'swapcycle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA2-nXNWainTRFjsdnSPrJ1TlkCu0wN3I',
    appId: '1:598228048901:ios:6289574612bd6bfed0106c',
    messagingSenderId: '598228048901',
    projectId: 'swapcycle',
    storageBucket: 'swapcycle.firebasestorage.app',
    iosBundleId: 'com.example.swapcycleUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA2-nXNWainTRFjsdnSPrJ1TlkCu0wN3I',
    appId: '1:598228048901:ios:6289574612bd6bfed0106c',
    messagingSenderId: '598228048901',
    projectId: 'swapcycle',
    storageBucket: 'swapcycle.firebasestorage.app',
    iosBundleId: 'com.example.swapcycleUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYfbep-1t1jRfBin9EnsP7QwEeSYZtE-g',
    appId: '1:598228048901:web:70699037cecc2c58d0106c',
    messagingSenderId: '598228048901',
    projectId: 'swapcycle',
    authDomain: 'swapcycle.firebaseapp.com',
    storageBucket: 'swapcycle.firebasestorage.app',
    measurementId: 'G-PTQ5ZRDTF0',
  );
}
