import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'auth_gate.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SwapCycleApp());
}

class SwapCycleApp extends StatelessWidget {
  const SwapCycleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SwapCycle',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
        useMaterial3: true,
      ),
      home: const AuthGate(), // was ListingFeedScreen()
    );
  }
}

class Listing {
  final String id;
  final String owner;
  final String item;
  final String category;
  final String brand;
  final String condition;

  const Listing({
    required this.id,
    required this.owner,
    required this.item,
    required this.category,
    required this.brand,
    required this.condition,
  });

  // Keeps the same field names your Python prototype's user/listing dicts
  // use, so this maps straight onto normalize_preference()'s expected shape
  // once the bridge is built.
  factory Listing.fromFirestore(DocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data()!;
    return Listing(
      id: doc.id,
      owner: data['owner'] as String? ?? '',
      item: data['item'] as String? ?? '',
      category: data['category'] as String? ?? '',
      brand: data['brand'] as String? ?? '',
      condition: data['condition'] as String? ?? '',
    );
  }
}

class ListingFeedScreen extends StatelessWidget {
  const ListingFeedScreen({super.key});

  IconData _iconForCategory(String category) {
    switch (category.toLowerCase()) {
      case 'bicycle':
        return Icons.pedal_bike;
      case 'guitar':
        return Icons.music_note;
      case 'camera':
        return Icons.camera_alt;
      default:
        return Icons.inventory_2;
    }
  }

  @override
  Widget build(BuildContext context) {
    final listingsRef = FirebaseFirestore.instance
        .collection('listings')
        .orderBy('item');

    return Scaffold(
      appBar: AppBar(
        title: const Text('SwapCycle'),
        centerTitle: true,
      ),
      body: StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
        stream: listingsRef.snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(child: Text('Error loading listings: ${snapshot.error}'));
          }
          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }

          final docs = snapshot.data!.docs;
          if (docs.isEmpty) {
            return const Center(
              child: Padding(
                padding: EdgeInsets.all(24),
                child: Text(
                  'No listings yet. Add documents to the "listings" '
                  'collection in Firestore to see them here.',
                  textAlign: TextAlign.center,
                ),
              ),
            );
          }

          final listings = docs.map(Listing.fromFirestore).toList();

          return ListView.builder(
            padding: const EdgeInsets.all(12),
            itemCount: listings.length,
            itemBuilder: (context, index) {
              final listing = listings[index];
              return Card(
                margin: const EdgeInsets.symmetric(vertical: 6),
                child: ListTile(
                  leading: CircleAvatar(
                    child: Icon(_iconForCategory(listing.category)),
                  ),
                  title: Text('${listing.item} — ${listing.brand}'),
                  subtitle: Text('Owned by ${listing.owner} · ${listing.condition} condition'),
                  trailing: const Icon(Icons.chevron_right),
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => const PreferenceInputScreen(),
                      ),
                    );
                  },
                ),
              );
            },
          );
        },
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () {
          Navigator.push(
            context,
            MaterialPageRoute(
              builder: (context) => const PreferenceInputScreen(),
            ),
          );
        },
        icon: const Icon(Icons.add),
        label: const Text('Request Swap'),
      ),
    );
  }
}

class PreferenceInputScreen extends StatefulWidget {
  const PreferenceInputScreen({super.key});

  @override
  State<PreferenceInputScreen> createState() => _PreferenceInputScreenState();
}

class _PreferenceInputScreenState extends State<PreferenceInputScreen> {
  final TextEditingController _controller = TextEditingController();
  bool _submitting = false;
  String? _submittedText;
  String? _error;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _submitPreference() async {
    final text = _controller.text.trim();
    if (text.isEmpty) return;

    setState(() {
      _submitting = true;
      _error = null;
    });

    try {
      // Schema deliberately mirrors the input `normalize_preference()`
      // expects on the Python side, plus a status flag so a future
      // Cloud Function trigger knows which docs still need processing.
      await FirebaseFirestore.instance.collection('preferences').add({
        'rawText': text,
        'submittedAt': FieldValue.serverTimestamp(),
        'status': 'pending', // pending -> processed once AI bridge exists
      });

      setState(() {
        _submittedText = text;
        _controller.clear();
      });
    } catch (e) {
      setState(() {
        _error = 'Failed to submit: $e';
      });
    } finally {
      setState(() {
        _submitting = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('What are you looking for?')),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            const Text(
              'Describe what you want in your own words. '
              'This gets normalized by SwapCycle\'s AI before matching.',
              style: TextStyle(color: Colors.grey),
            ),
            const SizedBox(height: 16),
            TextField(
              controller: _controller,
              maxLines: 3,
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                hintText: 'e.g. I want a beginner-friendly Yamaha guitar, good condition is fine.',
              ),
            ),
            const SizedBox(height: 12),
            ElevatedButton(
              onPressed: _submitting ? null : _submitPreference,
              child: _submitting
                  ? const SizedBox(
                      height: 18,
                      width: 18,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Text('Submit Preference'),
            ),
            if (_error != null) ...[
              const SizedBox(height: 12),
              Text(_error!, style: const TextStyle(color: Colors.red)),
            ],
            if (_submittedText != null) ...[
              const SizedBox(height: 24),
              const Text('Saved to Firestore (preferences collection):',
                  style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Card(
                color: Theme.of(context).colorScheme.surfaceContainerHighest,
                child: Padding(
                  padding: const EdgeInsets.all(12),
                  child: Text(_submittedText!),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}